name: 'dema'
version: '1.0.0'

profile: 'dema'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  dema:
    staging:
      +materialized: view
    
    intermediate:
      +materialized: ephemeral
    
    marts:
      +materialized: table
